### ISSUE TITLE
open card (current song playing) doesn't toggle back to small card when clicked again

### ISSUE THREAD

**Issue by suymilk** [nprapps/austin#103]
It instead restarts the song as if clicking it for the first time, with no changes in appearance.

**Comment by onyxfish** [comment]
@dannydb My thinking is that clicking the open card doesn't do anything, does that sound right?

**Comment by dannydb** [comment]
Yup! That's what I was thinking as well.

**Comment by Lalajohnson** [comment]
Hey for some reason I'm on this chain and I'm not on this project. How do I get off of the chain? It's sending me like 30 emails a day! Ack!
-LA Johnson

Sent from my iPhone

On Jan 30, 2015, at 10:45 AM, Danny DeBelius <notifications@github.com<mailto:notifications@github.com>> wrote:

Yup! That's what I was thinking as well.
