### ISSUE TITLE
After clicking back to a previous song, refreshing plays last song on the history list

### ISSUE THREAD

**Issue by suymilk** [nprapps/austin#145]
Refreshing should make the last song played play, not the last song on the history list

**Comment by suymilk** [comment]
This happens because playedSongs is not reflecting a technically accurate history; for example, out of A B C D, if B is played again, playedSongs = [A, B, C, D] not [A, B, C, D, B]. Argh.

**Comment by onyxfish** [comment]
Not a bug, I think this is the behavior we want. Will wait to see if anyone complains.
