### ISSUE TITLE
Bring back song count 

### ISSUE THREAD

**Issue by suymilk** [nprapps/austin#147]
Looks like this got deleted by accident? It was above the audio player controls. (you can put it somewhere that won't mess up the dimensions)

**Comment by dannydb** [comment]
It’s still there. Just moved in the DOM and hidden by other elements while I was debugging song transitions. Closing this as a dupe of #142.

**Comment by suymilk** [comment]
Ooh, gotcha.

On February 9, 2015 at 1:13:24 PM, Danny DeBelius (notifications@github.com) wrote:

It’s still there. Just moved in the DOM and hidden by other elements while I was debugging song transitions. Closing this as a dupe of #142.
