### ISSUE TITLE
IE 11: Fullscreen breaks view

### ISSUE THREAD

**Issue by suymilk** [nprapps/austin#195]
Exiting returns to normal.

![screen shot 2015-02-13 at 1 37 53 pm](https://cloud.githubusercontent.com/assets/5899885/6193070/d59bb9f6-b385-11e4-9b77-b8966e8eea41.png)

**Comment by suymilk** [comment]
Update: can't replicate it anymore. Might've been an isolated bug.

**Comment by onyxfish** [comment]
Maybe resize handler isn't firing on fullscreen? Do we need to invoke manually?
