### ISSUE TITLE
"Get the song" shows up even if there are no ways to get the song

### ISSUE THREAD

**Issue by onyxfish** [nprapps/austin#261]
![screen shot 2015-03-03 at 8 30 12 am](https://cloud.githubusercontent.com/assets/33046/6463425/0fc61416-c180-11e4-9708-94d6e890db1c.png)

**Comment by onyxfish** [comment]
Actually, this is something else. Not seeing "Get the song" stuff on desktop at all. Raising priority. @dannydb

**Comment by onyxfish** [comment]
Seeing this in prod, but not locally.

**Comment by onyxfish** [comment]
This only seems to be happening to me... Firefox. Did not happen on Becky or Emily's machines

**Comment by onyxfish** [comment]
Not showing up at small breakpoints in this particular browser either. I have no idea what's going on.

**Comment by onyxfish** [comment]
Demoting this since no one else sees it. Maybe @dannydb will have an idea when he gets in.

**Comment by suymilk** [comment]
Boop. I decided to check out Austin 100 again today and @onyxfish's original problem is happening to me, except for me it's on Chrome. Resizing does not solve the issue. Tried Safari and Firefox but works fine on those.

**Comment by dannydb** [comment]
Summer!!!

Chrome on desktop? Really? What song/artist was it?

**Comment by suymilk** [comment]
Hi!!!

It’s all of them! There’s only streaming info and not download info. I checked the data spreadsheet to make sure I didn’t just randomly get 20-some songs that didn’t have download info. (but regardless, there should be a ‘get the song’ with free download link, shouldn’t there?)

Maybe the Korean internet is somehow making it funky? I don’t know how or why that’d be a thing.

On March 16, 2015 at 11:48:59 PM, Danny DeBelius (notifications@github.com) wrote:

Summer!!!

Chrome on desktop? Really? What song/artist was it?

**Comment by suymilk** [comment]
![screen shot 2015-03-17 at 8 53 57 am](https://cloud.githubusercontent.com/assets/5899885/6678883/bbc84bcc-cc83-11e4-9963-1313429cde01.png)

**Comment by dannydb** [comment]
Weeeeeeird. I don’t get it:

![screen shot 2015-03-17 at 9 42 51 am](https://cloud.githubusercontent.com/assets/419297/6688481/139f301c-cc8a-11e4-9b72-bd2b388253cb.png)

No errors in the console?

**Comment by suymilk** [comment]
Nada. Wasn't the issue isolated for Chris as well? Probably not worth trying to fix.

**Comment by benrifkah** [comment]
In case anyone else runs across this I was getting this issue on Chrome today until I disabled Ad Block Plus.
