### ISSUE TITLE
Nail down format of the spreadsheet 

### ISSUE THREAD

**Issue by beckylettenberger** [nprapps/austin#95]
So we know what to ask for

**Comment by onyxfish** [comment]
Proposed columns:
- id
- artist
- title
- song_art
- media_url
- rdio
- spotify
- itunes
- asin

**Comment by onyxfish** [comment]
Placeholder spreadsheet with SWL14 data: https://docs.google.com/spreadsheets/d/1zvJ-RLAOd8UujpwN_1v6QyvZDassZ1UcqigmlPl2nxA/edit#gid=0

**Comment by onyxfish** [comment]
- download_url
- facebook_link?
- bandcamp_link?
- twitter_link?
- other_link?
- sxsw_link?

**Comment by onyxfish** [comment]
Final format: https://docs.google.com/spreadsheets/d/1eJ4qkOXaLUvPaRvjjeplgWD7hZCnxW_By3FzrfF3wss/edit#gid=0
