### ISSUE TITLE
Don't add playing songs to the bottom of the list, play in place

### ISSUE THREAD

**Issue by onyxfish** [nprapps/austin#98]

**Comment by Lalajohnson** [comment]
Hey for some reason I'm on this chain and I'm not on this project. How do I get off of the chain? It's sending me like 30 emails a day! Ack!
-LA Johnson

Sent from my iPhone

On Jan 30, 2015, at 10:45 AM, Suyeon Son <notifications@github.com<mailto:notifications@github.com>> wrote:

Closed #98https://github.com/nprapps/austin/issues/98.
